export const ACTIONS = {
  CREATE_TASK: 'CREATE_TASK',
  CREATE_TASK_FAILED: 'CREATE_TASK_FAILED',
  CREATE_TASK_FULFILLED: 'CREATE_TASK_FULFILLED',

  REMOVE_TASK: 'REMOVE_TASK',
  REMOVE_TASK_FAILED: 'REMOVE_TASK_FAILED',
  REMOVE_TASK_FULFILLED: 'REMOVE_TASK_FULFILLED',

  UPDATE_TASK: 'UPDATE_TASK',
  UPDATE_TASK_FAILED: 'UPDATE_TASK_FAILED',
  UPDATE_TASK_FULFILLED: 'UPDATE_TASK_FULFILLED',

  FILTER_TASKS: 'FILTER_TASKS',
  LOAD_TASKS_FULFILLED: 'LOAD_TASKS_FULFILLED'
};
